language = "C"

[export]
include = ["xray_version", "init_asset_path", "start_xray_crash", "start_xray_logger", "start_xray_core", "shutdown_xray_core", "get_xray_statistics"]

[parse]
parse_deps = false
include = ["ffi"]