name: Build And Release CLI

on:
  push:
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-linux-windows:
    name: Build CLI - ${{ matrix.target }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
          - x86_64-pc-windows-gnu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install llvm-dev libclang-dev clang pkg-config libssl-dev protobuf-compiler make build-essential zip gzip -y

      - name: Install Cross
        run: |
          cargo install cross

      - name: Build
        run: |
          export CFG_COMMIT_HASH=`git log --pretty=format:'%h' -n 1`
          export CFG_COMMIT_DATE=`git log --format="%ci" -n 1`
          cross build --release --target ${{ matrix.target }} -p xray_bin

      - name: Rename Windows binary
        if: ${{ contains(matrix.target, 'windows') }}
        run: |
          mv target/${{ matrix.target }}/release/xray_bin.exe xray_bin-${{ matrix.target }}.exe

      - name: Rename Unix binary
        if: ${{ !contains(matrix.target, 'windows') }}
        run: |
          mv target/${{ matrix.target }}/release/xray_bin xray_bin-${{ matrix.target }}

      - name: Package Windows binary
        if: ${{ contains(matrix.target, 'windows') }}
        run: |
          zip -9 xray_bin-${{ matrix.target }}.zip xray_bin-${{ matrix.target }}.exe
          echo "ASSET_FILE=xray_bin-${{ matrix.target }}.zip" >> $GITHUB_ENV

      - name: Package Unix binary
        if: ${{ !contains(matrix.target, 'windows') }}
        run: |
          gzip -c xray_bin-${{ matrix.target }} > xray_bin-${{ matrix.target }}.gz
          echo "ASSET_FILE=xray_bin-${{ matrix.target }}.gz" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.ASSET_FILE }}
          path: ${{ env.ASSET_FILE }}

      - name: Upload asset to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: ${{ env.ASSET_FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    name: Build CLI - ${{ matrix.target }}
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-apple-darwin
          - x86_64-apple-darwin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: |
          brew install llvm protobuf

      - name: Add target
        run: |
          rustup target add ${{ matrix.target }}

      - name: Build Rust
        run: |
          export CFG_COMMIT_HASH=`git log --pretty=format:'%h' -n 1`
          export CFG_COMMIT_DATE=`git log --format="%ci" -n 1`
          cargo build --release --target ${{ matrix.target }} -p xray_bin

      - name: Rename binary
        run: |
          mv target/${{ matrix.target }}/release/xray_bin xray_bin-${{ matrix.target }}

      - name: Package binary
        run: |
          gzip -c xray_bin-${{ matrix.target }} > xray_bin-${{ matrix.target }}.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: xray_bin-${{ matrix.target }}.gz
          path: xray_bin-${{ matrix.target }}.gz

      - name: Upload macOS asset to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: xray_bin-${{ matrix.target }}.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}