name: Build And Release Mobile Libraries

on:
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-lib-apple:
    name: Build Apple Library
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: |
          cargo install cbindgen
          brew untap aws/tap || true
          brew install llvm unzip protobuf

      - name: Build Apple
        run: |
          ./xray_scripts/apple_build.sh

      - name: Create ZIP archive and checksums
        shell: bash
        run: |
          mv build/LibXrayCoreRust.xcframework .

          touch -mt $(date +%Y%m%d0000) LibXrayCoreRust.xcframework

          FILE=LibXrayCoreRust.xcframework.zip
          zip -9vr "$FILE" LibXrayCoreRust.xcframework

          DGST=$FILE.dgst

          for METHOD in {"md5","sha1","sha256","sha512"}
          do
            openssl dgst -$METHOD "$FILE" | sed 's/([^)]*)//g' >>"$DGST"
          done

          echo "ASSET_ZIP=$FILE" >> $GITHUB_ENV
          echo "ASSET_DGST=$DGST" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: LibXrayCoreRust.xcframework
          path: |
            ${{ env.ASSET_ZIP }}
            ${{ env.ASSET_DGST }}

      - name: Upload Apple library to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            ${{ env.ASSET_ZIP }}
            ${{ env.ASSET_DGST }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-lib-android:
    name: Build Android Library
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          submodules: true
          lfs: true

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies and Android SDK
        run: |
          cargo install cbindgen

          sudo apt update
          sudo apt install -y make llvm-dev libclang-dev clang pkg-config unzip curl default-jdk build-essential libssl-dev zip openssl

          export ANDROID_HOME=/tmp/Android/sdk
          export NDK_HOME=/tmp/Android/sdk/ndk/28.2.13676358
          export PATH=$ANDROID_HOME/cmdline-tools/bin:$PATH

          cd /tmp/
          curl -OL https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
          unzip commandlinetools-linux-6858069_latest.zip

          mkdir -p $ANDROID_HOME
          mv cmdline-tools $ANDROID_HOME

          yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses
          $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME "ndk;28.2.13676358" "platforms;android-21"

      - name: Build Android
        run: |
          export ANDROID_HOME=/tmp/Android/sdk
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          export ANDROID_NDK_HOME=/tmp/Android/sdk/ndk/28.2.13676358
          export ANDROID_NDK=/tmp/Android/sdk/ndk/28.2.13676358
          export OPENSSL_DIR=$(pkg-config --variable=prefix openssl)

          ./xray_scripts/android_build.sh all

      - name: Create ZIP archive and checksums
        shell: bash
        run: |
          mv build/LibXrayCoreRust.aar .

          touch -mt $(date +%Y%m%d0000) LibXrayCoreRust.aar

          FILE=LibXrayCoreRust.aar.zip
          zip -9vr "$FILE" LibXrayCoreRust.aar

          DGST=$FILE.dgst

          for METHOD in {"md5","sha1","sha256","sha512"}
          do
            openssl dgst -$METHOD "$FILE" | sed 's/([^)]*)//g' >>"$DGST"
          done

          echo "ASSET_ZIP=$FILE" >> $GITHUB_ENV
          echo "ASSET_DGST=$DGST" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: LibXrayCoreRust.aar
          path: |
            ${{ env.ASSET_ZIP }}
            ${{ env.ASSET_DGST }}

      - name: Upload Android library to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            ${{ env.ASSET_ZIP }}
            ${{ env.ASSET_DGST }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}