name: Build And Release CLI

on:
  push:
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-linux-windows:
    name: Build CLI - ${{ matrix.target }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
          - x86_64-pc-windows-gnu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install llvm-dev libclang-dev clang pkg-config libssl-dev protobuf-compiler make build-essential zip openssl -y

      - name: Install Cross
        run: |
          cargo install cross

      - name: Build
        run: |
          export CFG_COMMIT_HASH=`git log --pretty=format:'%h' -n 1`
          export CFG_COMMIT_DATE=`git log --format="%ci" -n 1`
          cross build --release --target ${{ matrix.target }} -p xray_bin

      - name: Prepare build assets
        run: |
          mkdir -p build_assets

          if [[ "${{ contains(matrix.target, 'windows') }}" == "true" ]]; then
            cp target/${{ matrix.target }}/release/xray_bin.exe build_assets/xray_bin.exe
          else
            cp target/${{ matrix.target }}/release/xray_bin build_assets/xray_bin
          fi

      - name: Create ZIP archive and checksums
        shell: bash
        run: |
          pushd build_assets || exit 1
          touch -mt $(date +%Y%m%d0000) *
          zip -9vr ../Xray-${{ matrix.target }}.zip .
          popd || exit 1

          FILE=./Xray-${{ matrix.target }}.zip
          DGST=$FILE.dgst

          for METHOD in {"md5","sha1","sha256","sha512"}
          do
            openssl dgst -$METHOD $FILE | sed 's/([^)]*)//g' >>$DGST
          done

          echo "ASSET_ZIP=Xray-${{ matrix.target }}.zip" >> $GITHUB_ENV
          echo "ASSET_DGST=Xray-${{ matrix.target }}.zip.dgst" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: Xray-${{ matrix.target }}
          path: |
            ${{ env.ASSET_ZIP }}
            ${{ env.ASSET_DGST }}

      - name: Upload asset to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            ${{ env.ASSET_ZIP }}
            ${{ env.ASSET_DGST }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    name: Build CLI - ${{ matrix.target }}
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-apple-darwin
          - x86_64-apple-darwin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: |
          brew untap aws/tap || true
          brew install llvm protobuf

      - name: Add target
        run: |
          rustup target add ${{ matrix.target }}

      - name: Build Rust
        run: |
          export CFG_COMMIT_HASH=`git log --pretty=format:'%h' -n 1`
          export CFG_COMMIT_DATE=`git log --format="%ci" -n 1`
          cargo build --release --target ${{ matrix.target }} -p xray_bin

      - name: Prepare build assets
        run: |
          mkdir -p build_assets
          cp target/${{ matrix.target }}/release/xray_bin build_assets/xray_bin

      - name: Create ZIP archive and checksums
        shell: bash
        run: |
          pushd build_assets || exit 1
          touch -mt $(date +%Y%m%d0000) *
          zip -9vr ../Xray-${{ matrix.target }}.zip .
          popd || exit 1

          FILE=./Xray-${{ matrix.target }}.zip
          DGST=$FILE.dgst

          for METHOD in {"md5","sha1","sha256","sha512"}
          do
            openssl dgst -$METHOD $FILE | sed 's/([^)]*)//g' >>$DGST
          done

          echo "ASSET_ZIP=Xray-${{ matrix.target }}.zip" >> $GITHUB_ENV
          echo "ASSET_DGST=Xray-${{ matrix.target }}.zip.dgst" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: Xray-${{ matrix.target }}
          path: |
            ${{ env.ASSET_ZIP }}
            ${{ env.ASSET_DGST }}

      - name: Upload macOS asset to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            ${{ env.ASSET_ZIP }}
            ${{ env.ASSET_DGST }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}